# Configuration sample.

[general]
host = "0.0.0.0"
http_port = 81
#domain must be changed to reflect name.tld of your infrastructure
domain = "cmccoy1.click" 
db_path = "/home/user/data/domains.sqlite"

[pdns]
api_ttl = 1
dns_ttl = 86400
tunnel_ttl = 60
socket_path = "/tmp/pdns_tunnel.sock"
caa_records = [
  "0 issue \"letsencrypt.org\"",
]
mx_records = []
#this needs to reflect the public ip address of the registration server
ns_records = [
  [ "ns1.cmccoy1.click", "13.58.12.155" ],
]
txt_records = []
#This SOA needs to reflect whatever your DNS provider gives you/whatever you have created as the SOA
soa_record = "ns1.cmccoy1.click awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400"
#this is the IP address of the registration server
www_addresses = [
  "13.58.12.155",
]

  [pdns.geoip]
  default = "13.58.12.155"
 # database = "./test-data/GeoLite2-Country_20180206/GeoLite2-Country.mmdb"

    [pdns.geoip.continent]
   # AF = "1.2.3.4"
    #AN = "2.3.4.5"
    #AS = "3.4.5.6"
    #EU = "4.5.6.7"
    #NA = "5.6.7.8"
    #OC = "6.7.8.9"
    #SA = "9.8.7.6"

[email]
server = "smtp.gmail.com"
user = "collenlmccoy@gmail.com"
password = "******"
sender = "accounts@cmccoy1.click"
reclamation_title = "Reclaim your WebThings Gateway Domain"
reclamation_body = """Hello,
<br>
<br>
Your reclamation token is: {token}
<br>
<br>
If you did not request to reclaim your gateway domain, you can ignore this email."""
confirmation_title = "Welcome to your WebThings Gateway"
confirmation_body = """Hello,
<br>
<br>
Welcome to your WebThings Gateway! To confirm your email address, navigate to <a href="{link}">{link}</a>.
<br>
<br>
Your gateway can be accessed at <a href="https://{domain}">https://{domain}</a>."""
success_page = """<!DOCTYPE html>
<html>
  <head><title>Email Confirmation Successful!</title></head>
  <body>
    <h1>Thank you for verifying your email.</h1>
  </body>
</html>"""
error_page = """<!DOCTYPE html>
<html>
  <head><title>Email Confirmation Error!</title></head>
  <body>
    <h1>An error happened while verifying your email.</h1>
  </body>
</html>"""
